run:
  timeout: 5m
linters:
  enable-all: true
  disable:
    # maligned # deprecated 1.38
    - interfacer # deprecated 1.38
    - scopelint # deprecated 1.39
    - golint # deprecated 1.41
    - exhaustivestruct # deprecated 1.46
    - funlen
    - dupl
    - wsl
    - gomnd
    - goerr113 
    - nestif
    - paralleltest
    - gci
    - cyclop
    - forcetypeassert
    - varnamelen
    - maintidx
    - nonamedreturns
    - exhaustruct
linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default
    min-complexity: 70
  gocognit:
    # minimal code complexity to report, 30 by default
    min-complexity: 160
  gofumpt:
    # Choose whether to use the extra rules.
    extra-rules: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
issues:
  exclude-rules:
    - text: "TLS InsecureSkipVerify set true"
      linters:
        - gosec
   