run:
  timeout: 5m
linters:
  enable-all: true
  disable:
    - maligned # deprecated 1.38
    - interfacer # deprecated 1.38
    - scopelint # deprecated 1.39
    - golint # deprecated 1.41
    - funlen
    - dupl
    - wsl
    - gomnd
    - goerr113 
    - nestif
    - exhaustivestruct
    - paralleltest
    - gci
    - cyclop
    - forcetypeassert
    - wrapcheck
    - errorlint
    - varnamelen
    - maintidx
linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default
    min-complexity: 70
  gocognit:
    # minimal code complexity to report, 30 by default
    min-complexity: 160
issues:
  exclude-rules:
    - text: "TLS InsecureSkipVerify set true"
      linters:
        - gosec
   