linters:
  enable-all: true
  disable:
    - dupl
    - funlen
    - wsl
    - nestif
    - errorlint
    - goerr113
    - exhaustivestruct
    - wrapcheck
linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default
    min-complexity: 70
  gocognit:
    # minimal code complexity to report, 30 by default
    min-complexity: 160
issues:
  exclude-rules:
    - text: "TLS InsecureSkipVerify set true"
      linters:
        - gosec
