name: Terraform fmt
on: [push, pull_request]
jobs:
  terrafmt:
    name: terrafmt
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: Check out terrafmt code
        uses: actions/checkout@v2
        with:
          repository: katbyte/terrafmt
          ref: v0.3.0
          path: terrafmt
      - name: Build terrafmt bin
        run: cd terrafmt && go install ./... && cd ${GITHUB_WORKSPACE}
      - name: Terrafmt diff on html.markdown
        run: find docs | egrep ".md$" | sort | while read f; do terrafmt diff $f; done >> /tmp/results.docs.md
      - name: Terrafmt diff on _test.go
        run: find . | egrep "_test.go$" | sort | while read f; do terrafmt diff $f; done >> /tmp/results.test.go
      - name: Generate error if results not empty
        run: |
          if [[ -s /tmp/results.docs.md || -s /tmp/results.test.go ]] ; then 
            cat /tmp/results.docs.md
            cat /tmp/results.test.go
            echo "terraform blocks in docs/test-go files not being properly formatted"
            exit 1
          fi